server:
  port: 80


eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
feign:
  hystrix:
    enabled: true

spring:
  # thymeleaf模板引擎
  thymeleaf:
    cache: false
    mode: HTML5
    content-type: text/html
    encoding: utf-8