server:
  port: 8770

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
#    register-with-eureka: false
#    fetch-registry: false
  instance:
    prefer-ip-address: true

zuul:
  routes:
    mydept.serviceId: microservice-dept
    mydept.path: /mydept/**
  #ignored-services: microservice-dept
  ignored-services: "*"
  prefix: /csl